### PR TITLE
add optional `canonicalUrl` to article schema

### PR DESCRIPTION
**Pull request by srilq**
This looks correct to me, but I've never looked at this before so would appreciate review from @thekemkid. 🤔

### CODE REVIEW

**Comment by srilq** [comment]
@thekemkid what's the difference between `.allow('').default('')` and `.optional()`?

**Comment by thekemkid** [comment]
@srilq There both different forms for `optional`. The first form allows empty strings as properties, and defaults to that value if the property is undefined. the second form doesn't allow empty strings if the property exists and leaves the value as undefined if the property is not supplied. It changes the semantics slightly for how you check properties existing, and allows data sources to be a little bit more flexible, using `''` for values vs leaving values `undefined`

Do you want to cut the release yourself? I usually push the version bump to master directly after merging the PR.

**Comment by srilq** [comment]
@thekemkid this is `0.5.1` right? I'm gonna bump the version in `package.json` and run
```
$ npm i
$ git add .
$ git commit
$ git push
$ npm publish
```

**Comment by thekemkid** [comment]
you can use `npm version patch` which adds the commit for you & will tag it for you. LGTM though!

**Comment by srilq** [comment]
I had no idea... that's useful.

**Pull request merged**
