### PR TITLE
validate galleries and photos

### PR DESCRIPTION
**Pull request by michael-zucker**
#### This resolves Clubhouse issue: <issue>

- [ x] Tests have been written
- [x ] All TODOs have a task created and assigned
- [x ] Any tech debt raised as cards in Clubhouse
- [x ] Checked that the new code runs properly

### CODE REVIEW

**Comment by srilq** [comment]
Assuming this means we are supporting migrating both galleries and photos as standalone entities? Otherwise, it would be misleading to allow validation of photos and not other entities.

**Comment by thekemkid** [comment]
@srilq We just want to expose the ability to validate them as standalone entities, because of the issue with `inline` not being able to infer the type to validate. It caught us out here trying to get a gallery validated that was nested within an article.

**Comment by srilq** [comment]
@thekemkid Ah, I see! Makes sense. Any reason not to also expose the other documented models: advertiser/contributor/category?

**Comment by michael-zucker** [comment]
@srilq because `inline` only uses gallery, photo, etc.

**Comment by thekemkid** [comment]
Also of note: this is not really addressing the issue of bad inline errors, but it at least gives _some_ way of figuring out what is wrong! We'll need to address this properly in a future PR, this was just a hack.

**Comment by srilq** [comment]
This should be another new major version I think.

I'm just wondering: is the idea to, for example, update the dashboard UI to say "Validate Entity" rather than "Validate Article"? It might not be clear that this only refers to articles, galleries and photos (and not other entities) which is why I wonder if we could just expose all the models in the validator. But it's fine, just a minor thing.

**Comment by almostagile** [comment]
Since this change now means that this API accepts gallery and photo as well as article and nativearticle, Flyway service is going to need a new way to validate the response from the article endpoint https://github.com/conde-nast-international/flyway-service/blob/master/src/integration/IntegrationApiClient.js#L44.

**Comment by srilq** [comment]
@almostagile Good point – can just check the type though, right?

**Comment by almostagile** [comment]
@srilq It feels like it is now time for this module to expose separate schemas rather than just a single function.

**Comment by srilq** [comment]
@almostagile Yeah I agree, but I guess that can be a separate change.

**Pull request merged**
